services:
  - type: web
    name: wasteland-news
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NEWS_API_KEY_1
        sync: false
      - key: NEWS_API_KEY_2
        sync: false
      - key: PERPLEXITY_API_KEY
        sync: false
